### PR TITLE
docs:#524 list required S3 permissions

### PR DESCRIPTION
**Pull request by micheleRP**
resolves #524 

preview: 

- https://deploy-preview-800--redpanda-documentation.netlify.app/docs/data-management/tiered-storage/#configuring-amazon-s3
- https://deploy-preview-800--redpanda-documentation.netlify.app/docs/security/iam-roles/#amazon-web-services-prerequisites

### CODE REVIEW

**Comment by micheleRP** [comment]
Hi @daisukebe! This PR just adds the S3 permissions. Please let me know if this requires anything else: https://deploy-preview-800--redpanda-documentation.netlify.app/docs/data-management/tiered-storage/#configuring-amazon-s3. (Note that I still have some updates to make to the Tiered Storage & Data Archiving chapters. The 22.3 preview for this Tiered Storage page is [here](https://deploy-preview-790--redpanda-documentation.netlify.app/docs/platform/data-management/tiered-storage/#configure-cloud-storage).)

**Comment by daisukebe** [comment]
Thanks @micheleRP. It looks good to me. 
In addition to that, can you make a change to this page https://deploy-preview-800--redpanda-documentation.netlify.app/docs/security/iam-roles/?

```
A full access policy with all S3 permissions is required for Tiered Storage
```

This isn't true and the required permissions are the mentioned three.

**Comment by micheleRP** [comment]
Thanks @daisukebe. Please confirm if this page is correct: https://deploy-preview-800--redpanda-documentation.netlify.app/docs/security/iam-roles/#amazon-web-services-prerequisites

**Comment by daisukebe** [comment]
The changes look good to me. I'm doing one more clarification in terms of the `"s3:List*"` action mentioned in the IAM Roles page. Stay tuned.

**Comment by daisukebe** [comment]
All good. Thanks for making the change!

**Pull request closed without merging**
