### PR TITLE
Update serverless - retention size limit

### PR DESCRIPTION
**Pull request by kbatuigas**
[Deploy preview](https://deploy-preview-428--redpanda-docs-preview.netlify.app/current/deploy/deployment-option/cloud/serverless/#limits)

Remove 10GiB retention limit, per [this discussion](https://redpandadata.slack.com/archives/C02DKEQE50S/p1713298680985229)

### CODE REVIEW

**Review by Deflaimun — APPROVED** [review]

**Comment by supahcraig** [comment]
Looks good on the docs side, but is there a corresponding change that needs to be handled within core?   Just removing the item in the docs doesn't change any coded limitations within the product.

**Comment by kbatuigas** [comment]
> Looks good on the docs side, but is there a corresponding change that needs to be handled within core? Just removing the item in the docs doesn't change any coded limitations within the product.

@piyushredpanda @twmb would any of you be able to chime in?

**Comment by piyushredpanda** [comment]
> > Looks good on the docs side, but is there a corresponding change that needs to be handled within core? Just removing the item in the docs doesn't change any coded limitations within the product.
> 
> @piyushredpanda @twmb would any of you be able to chime in?

Nothing more needed from Core, the product capability is already there. @twmb could comment on any needed changes from serverless' end.

**Comment by kbatuigas** [comment]
> > > Looks good on the docs side, but is there a corresponding change that needs to be handled within core? Just removing the item in the docs doesn't change any coded limitations within the product.
> > 
> > 
> > @piyushredpanda @twmb would any of you be able to chime in?
> 
> Nothing more needed from Core, the product capability is already there. @twmb could comment on any needed changes from serverless' end.

Thank you @piyushredpanda - could I have you and/or @twmb approve this PR? We need at least one SME approval to get this merged.

**Comment by piyushredpanda** [comment]
Either @jan-g or @twmb would be better to approve it...

**Review by twmb — APPROVED** [review]

**Pull request merged**
