### PR TITLE
engine: create fix for long code wrap

### LINKED ISSUE #1301: MM2 Documentation has error message that runs off side of browser viewport
### Describe the Issue

Page: https://docs.redpanda.com/docs/manage/data-migration/

On the MM2 docs in the _Message Size_ section, we describe a java error message for `org.apache.kafka.common.errors.RecordTooLargeException` that scrolls off the right side of the screen. It ends up obscuring the right-side table of contents.

The error should probably be wordwrapped (or maybe pulled into a code block instead of an inline code segment) to improve readability.

Here's a screenshot on Chrome Version 110.0.5481.177 (Official Build) (arm64)

SCR-20230228-n6y

### PR DESCRIPTION
**Pull request by Deflaimun**
Resolves #1301 
Preview: 
https://deploy-preview-1307--redpanda-documentation.netlify.app/

### CODE REVIEW

**Review by JakeSCahill — APPROVED** [review]
Confirmed that this fixes the issue 😄 we might want to consider adding this property for all code blocks.

**Comment by Deflaimun** [comment]
@JakeSCahill Yeah. I was reluctant to remove this passage
https://github.com/redpanda-data/documentation/blob/dev/src/css/custom.css#L149

Because it does indeed make code fences look better. 
So I created this one-time fix. 

What do you guys think?
Should we remove the white-space: nowrap style? 

@shorgi

**Comment by shorgi** [comment]
> @JakeSCahill Yeah. I was reluctant to remove this passage https://github.com/redpanda-data/documentation/blob/dev/src/css/custom.css#L149
> 
> Because it does indeed make code fences look better. So I created this one-time fix.
> 
> What do you guys think? Should we remove the white-space: nowrap style?
> 
> @shorgi

Yes, I agree with making the line-wrap (or pre-wrap) as a global fix for <code>. (I think I made the original change and overlooked this page, my mistake!).

**Comment by Deflaimun** [comment]
Changed the fix to be a global pre-wrap @shorgi @JakeSCahill

**Review by JakeSCahill — APPROVED** [review]
LGTM

**Pull request merged**
