### PR TITLE
Document enable_schema_id_validation

### LINKED ISSUE #1695: Update schema ID validation enablement configuration docs
### Describe the Issue

Update schema ID validation docs to follow https://github.com/redpanda-data/redpanda/pull/11284

### PR DESCRIPTION
**Pull request by shorgi**
Fixes #1695 

Review deadline: Fri Jun 16

### CODE REVIEW

**Review by BenPope — APPROVED** [review]

**Comment by shorgi** [comment]
Don't merge this PR until an updated 23.2 Beta with this change is released. (@mattschumpert - when is the next 23.2 Beta release?)

**Comment by Feediver1** [comment]
image

Not part of this PR, but I think the navtree entry here should be "Server-Side Schema Validation" (see "Self-Hosted"--want these all to be consistent). Thx.

**Review by Feediver1 — APPROVED** [review]
lgtm--see comment on navtree entry

**Comment by shorgi** [comment]
Committed in branch `version-release-23-2` as c9a083d

**Pull request closed without merging**
