### PR TITLE
Clarify when controller snapshots are enabled

### PR DESCRIPTION
**Pull request by Feediver1**
Fixes https://github.com/redpanda-data/documentation-private/issues/2189

Preview:
[Controller partition and snapshots](https://deploy-preview-486--redpanda-docs-preview.netlify.app/current/get-started/architecture/#controller-partition-and-snapshots)

[Upgrades - Limitations](https://deploy-preview-486--redpanda-docs-preview.netlify.app/current/upgrade/rolling-upgrade/#limitations)

### CODE REVIEW

**Comment by Feediver1** [comment]
@ztlpn Thinking that now, the entire **Controller snapshots** entry in Upgrade Limitations should be removed, no?

**Comment by ztlpn** [comment]
> Thinking that now, the entire Controller snapshots entry in Upgrade Limitations should be removed, no?

@Feediver1 sounds good, it is only relevant for the 23.2 branch. Given that the docs are now versioned, it should just be removed in 24.1 and 23.3 branches.

**Comment by Feediver1** [comment]
@ztlpn I removed the limitation. We do not typically go back into older versions and add updates. So I think this is good to go.

**Comment by micheleRP** [comment]
@ztlpn: Is the correct term "controller partition" or "controller broker"? (See the current glossary entry for [controller broker](https://deploy-preview-486--redpanda-docs-preview.netlify.app/current/reference/glossary/#controller-broker).)

**Review by ztlpn — APPROVED** [review]

**Comment by ztlpn** [comment]
> Is the correct term "controller partition" or "controller broker"?

Both are valid terms. Controller partition is the partition present on all brokers that stores cluster metadata. Controller broker is the leader of this partition (one broker in the cluster).

Btw, I wonder where this came from:
> Controller responsibilities: Elect new partition leaders when a broker fails or is offline

This is true for kafka I think, but definitely not true for redpanda.

**Review by micheleRP — APPROVED** [review]
lgtm

**Comment by micheleRP** [comment]
> > Is the correct term "controller partition" or "controller broker"?
> 
> Both are valid terms. Controller partition is the partition present on all brokers that stores cluster metadata. Controller broker is the leader of this partition (one broker in the cluster).
> 
> Btw, I wonder where this came from:
> 
> > Controller responsibilities: Elect new partition leaders when a broker fails or is offline
> 
> This is true for kafka I think, but definitely not true for redpanda.

Thanks @ztlpn! We'll update the glossterm in a separate PR!

**Pull request merged**
