### PR TITLE
Kafka TLS encryption updates

### LINKED ISSUE #1856: Configure Kafka TLS Encryption - many issues
### Issue description

There are many issues with this page, from missing steps, to steps being out of sequence, to commands that are just plain incorrect.   This is my attempt to salvage this page rather than a ground up re-write.  There may be a followup request to add more relevant info, this is purely to make the document work/be correct throughout.  Happy to partner with whoever takes on this task to worth through the specifics to get it corrected.

## issue 1 - sequencing

Within the perquisites section there are two main sections:   "Create certificate signing requests" (aka Cert Signing) which is currently first in the doc, and then "Create a local CA for self-signed certificates" (aka Local CA).    These two sections need to be flipped in the sequencing of the document.   The reason being commands from the Cert Signing section rely on output from commands in the Local CA section.  

## issue 2 - missing generating the certificate signing request

Step 3 in the Local CA section, titled "Sign Certificates" requires the broker signing request (`broker.csr`) but the command to generate `broker.csr` is missing.   

## issue 3 - incorrect description in "Generate broker private key (broker.key)

Step 2 in the Local CA section, titled "Generate broker private key (broker.key), the table describes the output as "The public key certificate of the CA," but it is actually the private key for the broker.

## issue 4 - incorrect command for signing the broker certificate

Step 3 in the Local CA section uses the incorrect command to sign the broker cert, should use the `ca.crt` and `ca.cnf` along with the `ca.key`, rather than the `broker.cnf` and `broker.key`

## issue 5 - both the `broker.cnf` and the `ca.cnf` files are incorrect

There are some wrong values, extra sections, and missing sections in each of those files.   The `[ alt_names ]` section after the broker.cnf section would benefit from more example of usage.

## issue 6 - no mention of permissions nor the need to restart redpanda service

These 3 files need to be readable by redpanda, either through 444 permissions or chown to redpanda with 400 permissions:
* `broker.crt`
* `broker.key`
* `ca.crt`

and then once added to the `redpanda.yaml`, the redpanda service must be restarted for TLS to take effect, since the keys & certs are only read at startup.

### Updates to existing documentation

https://docs.redpanda.com/docs/manage/security/encryption/

I'm challenged by the best way to present these changes.   Happy to work hand in hand with anyone to help make this be a functioning document.   For ease of communication, I'm referring to the various document sections as:

* [Create certificate signing requests](https://docs.redpanda.com/docs/manage/security/encryption/#create-certificate-signing-requests) = "Cert Signing"
* [Create a local CA for self-signed certificates](https://docs.redpanda.com/docs/manage/security/encryption/#create-a-local-ca-for-self-signed-certificates) = "Local CA"

## Issue 1 - sequencing

Currently the Prerequisites section is staged with the Cert Signing before the Local CA.   The correct sequencing is as follows:

* Local CA
1.  https://docs.redpanda.com/docs/manage/security/encryption/#1-create-ca-configuration-file-cacnf
2. https://docs.redpanda.com/docs/manage/security/encryption/#2-generate-ca-private-key-and-public-certificate

* Cert Signing
1.  https://docs.redpanda.com/docs/manage/security/encryption/#1-create-broker-configuration-file-brokercnf
2. https://docs.redpanda.com/docs/manage/security/encryption/#2-generate-broker-private-key-brokerkey
3. https://docs.redpanda.com/docs/manage/security/encryption/#3-sign-certificates
4. https://docs.redpanda.com/docs/manage/security/encryption/#3-sign-certificates-1

## Issue 2 - missing generating broker cert signing request

Prior to Cert Signing step 3, this command must be run to generate the broker's certificate signing request

`openssl req -new -key broker.key -out broker.csr -nodes -config broker.cnf`

## Issue 3 - incorrect description in "Generate broker private key (broker.key)

https://docs.redpanda.com/docs/manage/security/encryption/#2-generate-broker-private-key-brokerkey

In the output table for this command, the Description should read "The private key certificate of the broker."

## Issue 4 - incorrect command for signing the broker certificate

https://docs.redpanda.com/docs/manage/security/encryption/#3-sign-certificates

The command should be:

```
touch index.txt
echo '01' > serial.txt
openssl ca -config ca.cnf -keyfile ca.key -cert ca.crt -extensions extensions -in broker.csr -out broker.crt -outdir . -batch

chown redpanda:redpanda broker.key broker.crt ca.crt
chmod 400 broker.key broker.crt ca.crt
```

## Issue 5 - both the `broker.cnf` and the `ca.cnf` files are incorrect

Corrected versions of the files are attached, extensions renamed to `.txt` to allow upload here.
[broker.txt](https://github.com/redpanda-data/documentation/files/12341248/broker.txt)
[ca.txt](https://github.com/redpanda-data/documentation/files/12341249/ca.txt)

In addition, the `[ alt_names ]` paragraph at the end of the broker.cnf section could be more helpful by further adding:

In addition, you could also configure alternative names using the public or private IP addresses of all your brokers in this way:

```
[ alt_names ]
IP.1 = 10.0.8.1
IP.2 = 10.0.8.2
IP.3 = 10.0.8.3
```
 

## Issue 6  - no mention of permissions nor the need to restart redpanda service

The permissions/ownership is resolved in the changes made as part of Issue 4 above.    Once the user makes the changes proposed to `redpanda.yaml` in the [Configure TLS section](https://docs.redpanda.com/docs/manage/security/encryption/#configure-tls) the user needs to know that it is necessary to restart redpanda services because the keys & certificates are only read at startup.  If there are TLS related changes made to `redpanda.yaml` they will not be known to Redpanda until after a restart.

`systemctl restart redpanda`

### Link to Redpanda Slack conversation

https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1685997845902669

### PR DESCRIPTION
**Pull request by Feediver1**
Fixes #1856 

[Preview](https://deploy-preview-1878--legacy-docusaurus-site.netlify.app/docs/manage/security/encryption/)

### CODE REVIEW

**Review by supahcraig — APPROVED** [review]

**Comment by micheleRP** [comment]
@supahcraig are there no edits required for the [Kubernetes version of this page](https://deploy-preview-1878--legacy-docusaurus-site.netlify.app/docs/manage/kubernetes/security/kubernetes-tls/)?

**Comment by supahcraig** [comment]
> 

I'm sure there are changes required for the k8's page, however I didn't do any work on that front so I didn't submit any changes.

**Comment by JakeSCahill** [comment]
@supahcraig the only change I’m aware of is this one: https://github.com/redpanda-data/documentation/issues/1865

**Comment by Feediver1** [comment]
@JakeSCahill: CS provided these updates for Linux. I did not get any guidance wrt k8s. Will be merging/closing this PR, but I encourage you to share this info and find out if there are any updates required on the k8s side.

**Review by micheleRP — APPROVED** [review]
lgtm

**Pull request merged**
