### PR TITLE
docs:#659 Correct address in docker-compose.yml

### LINKED ISSUE #659: Customer Feedback: Update Docker Compose address
### Describe the Issue

See email to docs on Sept 21, 2022 at 3:23PM PDT.
Customer feedback on Docker Compose address.
From: Jason Hancock (jason@jasonhancock.com)

### Updates to existing documentation

Link to doc: https://docs.redpanda.com/docs/quickstart/quick-start-docker/#bring-up-a-docker-compose-file

Topic to update: Bring up a docker-compose file

Description from the customer's email:

The docker-compose instructions https://docs.redpanda.com/docs/quickstart/quick-start-docker/#bring-up-a-docker-compose-file don't work. You have to update the "localhost:9092" to "redpanda:9092" for both the 
--advertise-kafka-addr and --advertise-pandaproxy-addr flags.

Otherwise, if you try to do something like run a container to bootstrap rpk topics, you end up getting a "cannot connect to [127.0.0.1:9092](http://127.0.0.1:9092/)" error.

#### This will fail:

version: "3.9"
services:
  redpanda:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://[0.0.0.0:29092](http://0.0.0.0:29092/),OUTSIDE://[0.0.0.0:9092](http://0.0.0.0:9092/)
    - --advertise-kafka-addr
    - plaintext://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://[0.0.0.0:28082](http://0.0.0.0:28082/),OUTSIDE://[0.0.0.0:8082](http://0.0.0.0:8082/)
    - --advertise-pandaproxy-addr
    - plaintext://redpanda:28082,OUTSIDE://localhost:8082
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092
    expose:
    - "9092"

  redpandasetup:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    depends_on:
      - redpanda
    restart: "no"
    environment:
      REDPANDA_BROKERS: redpanda:9092
    entrypoint: sh -c "sleep 3 && rpk topic create incoming"

#### This will work:

version: "3.9"
services:
  redpanda:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://[0.0.0.0:29092](http://0.0.0.0:29092/),OUTSIDE://[0.0.0.0:9092](http://0.0.0.0:9092/)
    - --advertise-kafka-addr
    - plaintext://redpanda:29092,OUTSIDE://redpanda:9092
    - --pandaproxy-addr
    - PLAINTEXT://[0.0.0.0:28082](http://0.0.0.0:28082/),OUTSIDE://[0.0.0.0:8082](http://0.0.0.0:8082/)
    - --advertise-pandaproxy-addr
    - plaintext://redpanda:28082,OUTSIDE://redpanda:8082
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092
    expose:
    - "9092"

  redpandasetup:
    image: [docker.redpanda.com/vectorized/redpanda:v22.2.3](http://docker.redpanda.com/vectorized/redpanda:v22.2.3)
    depends_on:
      - redpanda
    restart: "no"
    environment:
      REDPANDA_BROKERS: redpanda:9092
    entrypoint: sh -c "sleep 3 && rpk topic create incoming"

### PR DESCRIPTION
**Pull request by AnneLeeperRP**
Corrects the address in `docker-compose.yml`. This PR addresses customer feedback.
Resolves #659

### CODE REVIEW

**Review by JakeSCahill — APPROVED** [review]
Tested locally and it works.

**Comment by Feediver1** [comment]
Status: Pinged #team-customer-success: https://redpandadata.slack.com/archives/C03KAHQ776C/p1670879416190609
Need guidance on the correct entry in the yaml file.

**Review by vuldin — CHANGES_REQUESTED** [review]
The issue with setting `localhost` to `redpanda` is that it assumes `redpanda` is a resolvable hostname on the host. By default this is not the case (for for `localhost` it is). This change doesn't stop redpanda from starting since it's only related to the advertised listener, but using `rpk topic create log` from the host doesn't work since it can't resolve the hostname `redpanda`.

@tmgstevens made a comment on the issue that gives some additional details: https://github.com/redpanda-data/documentation/issues/659#issuecomment-1348331963

**Comment by JakeSCahill** [comment]
closing this as it's resolved in #1034

**Pull request closed without merging**
