### PR TITLE
Update to remove the image tag  version for operator helm command

### PR DESCRIPTION
**Pull request by bhataprameya**
- Update to remove the image tag  version for operator helm command

### CODE REVIEW

**Comment by JakeSCahill** [comment]
Thanks for your contribution @bhataprameya. You're right, the current tag should be updated. However, I believe the advice is to always start with the latest version of the operator, so I think it may be best to just remove the line where we set the image tag of the operator chart.

@alejandroEsc or @RafalKorepta WDYT?

**Comment by RafalKorepta** [comment]
> However, I believe the advice is to always start with the latest version of the operator, so I think it may be best to just remove the line where we set the image tag of the operator chart.

I agree. It's easier when documentation doesn't have constantly moving target.

**Comment by bhataprameya** [comment]
Updated The PR to remove the image tag

**Review by JakeSCahill — APPROVED** [review]
Thank you @bhataprameya 🎉

**Pull request merged**
