### PR TITLE
Merge 23.1 PRs into dev for self-test and log_segment_size 

### PR DESCRIPTION
**Pull request by shorgi**
Cherry-picked from branch `23.1` into `dev`:
- self-test (fdb82dd75bab1d74fd4ef836760825aa43b59d32) 
- log_segment_size property (e8190b94ff9a4e9b2722f6e745b7c5070843abbb)

### CODE REVIEW

**Comment by micheleRP** [comment]
Hi @shorgi. I realize this is just copying the beta content into dev, and I assume that beta content has already been doc-approved, right? Just for quality edits down the road:

**Comment by micheleRP** [comment]
If so, I won't do a whole other review of it. But I don't see the sidebars updates in this preview. It's in the PR, but I don't see it updated in preview. Maybe it just needs to be committed to see it in preview, but can you pls check? 
Also, for quality edits down the road: the cluster diagostics page uses both `run <rpk>` and `run the <rpk> command`, or similar variations. Recommend using one format consistently on the page.

**Comment by shorgi** [comment]
> Hi @shorgi. I realize this is just copying the beta content into dev, and I assume that beta content has already been doc-approved, right? Just for quality edits down the road:

Yes, this cherry-picks from the 23.1 (beta) branch two of my already approved PR merge-commits.  You can click on the commit links in the description to those merged PRs.

**Review by micheleRP — APPROVED** [review]
lgtm

**Comment by shorgi** [comment]
> If so, I won't do a whole other review of it. But I don't see the sidebars updates in this preview. It's in the PR, but I don't see it updated in preview. Maybe it just needs to be committed to see it in preview, but can you pls check? Also, for quality edits down the road: the cluster diagostics page uses both `run <rpk>` and `run the <rpk> command`, or similar variations. Recommend using one format consistently on the page.

Thanks @micheleRP , I confirmed in the preview that the 23.1 beta's sidebar has the expected self-test and cluster diagnostics links/pages. And I'll make those consistency edits in a future PR.

**Pull request merged**
