### PR TITLE
engine: add smart redirect to versioned content

### LINKED ISSUE #1516: Create a smart redirect mechanism
### Describe the Issue

Looking at the data that we have about 404s, it's safe to say that need a smart redirect mechanism to reduce user's frustration when navigating through the website.

We already have a lot of redirects on the _redirects file, but a smart redirect would help alleviate this problem.

### PR DESCRIPTION
**Pull request by Deflaimun**
Resolves #1516

### CODE REVIEW

**Review by shorgi — COMMENTED** [review]
- https://deploy-preview-1655--redpanda-documentation.netlify.app/docs/22.3/home/tiered-storage didn't redirect to https://deploy-preview-1655--redpanda-documentation.netlify.app/docs/22.3/manage/tiered-storage/. Shouldn't it redirect successfully?
- https://deploy-preview-1655--redpanda-documentation.netlify.app/docs/beta/home/kafka-clients redirected me to https://deploy-preview-1655--redpanda-documentation.netlify.app/docs/develop/kafka-clients/. Shouldn't it redirect to v23.2 Beta instead of 23.1?

**Comment by Deflaimun** [comment]
Beta is not covered in those redirects. The idea is that since those pages come and go, auto-redirecting to them can be a problem. 
I'm open to discussions tho. What do you guys think? @JakeSCahill @shorgi

**Comment by JakeSCahill** [comment]
> Beta is not covered in those auto redirects. The idea is that since those pages come and go, auto-redirecting to them can be a problem. I'm open to discussions tho. What do you guys think? @JakeSCahill @shorgi

Agreed.

**Comment by Deflaimun** [comment]
Found the bug with tiered storage. There's two pages named tiered-storage. The code can't decide which one to pick, so it picks neither.

**Review by shorgi — APPROVED** [review]

**Pull request merged**
