### PR TITLE
docs:#1183 remove extra deployment option

### PR DESCRIPTION
**Pull request by micheleRP**
resolves #1183 

preview: https://deploy-preview-1388--redpanda-documentation.netlify.app/docs/deploy/

### CODE REVIEW

**Comment by micheleRP** [comment]
Hi @jrkinley. Would you please review this and confirm if this covers what you wanted to see in #1265?

**Review by Deflaimun — APPROVED** [review]

**Comment by Deflaimun** [comment]
This is a good compromise on what users want and the tech impact on docs team.

**Comment by shorgi** [comment]
@micheleRP - on the `docs/home` landing page, we should also remove the `Choose a Deployment Option` link from the `Deploy` panel.  You can do that by removing this line: https://github.com/redpanda-data/documentation/blob/docs/%231183-remove-depoloyment-option/docs/home/homepage.js#L114

**Comment by micheleRP** [comment]
> @micheleRP - on the `docs/home` landing page, we should also remove the `Choose a Deployment Option` link from the `Deploy` panel. You can do that by removing this line: https://github.com/redpanda-data/documentation/blob/docs/%231183-remove-depoloyment-option/docs/home/homepage.js#L114

Done--thanks, @shorgi!

**Review by jrkinley — APPROVED** [review]

**Pull request merged**
