### PR TITLE
engine: add tech-preview to dropdown list

### PR DESCRIPTION
**Pull request by Deflaimun**
Resolves https://github.com/redpanda-data/documentation-private/issues/1985

Please also check the integrity of https://github.com/redpanda-data/docs/tree/technical-preview

### CODE REVIEW

**Comment by JakeSCahill** [comment]
@Feediver1 @Deflaimun didn't we agree to display Technical Preview as a version?

**Comment by mattschumpert** [comment]
I agree with Jake.  I think it makes more sense as a version

**Comment by Deflaimun** [comment]
Adding blocked label until a decision on Tech Preview is made @Feediver1 @mattschumpert

**Comment by Deflaimun** [comment]
This change will not go forward. Closing PR and ticket.

**Pull request closed without merging**
