### PR TITLE
Update description of redpanda_kafka_max_offset

### LINKED ISSUE #1770: Breaking changes to metric `redpanda_kafka_max_offset` in v23.2
### Issue description

As per the release note on https://github.com/redpanda-data/redpanda/pull/9334

"The public metrics "max_offset" now returns the high watermark suitable for calculating consumer lag. Prior to this change it returned the commit offset, which presented an off-by-one situation when calculating lag."

### Updates to existing documentation

* https://docs.redpanda.com/docs/beta/reference/public-metrics-reference/#redpanda_kafka_max_offset
* https://docs.redpanda.com/docs/beta/manage/kubernetes/monitor/#consumer-group-lag

### Link to Redpanda Slack conversation

* https://redpandadata.slack.com/archives/C05J8H3V4F2/p1689684552010719
* https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1687438537718949

### PR DESCRIPTION
**Pull request by shorgi**
Fixes #1770

### CODE REVIEW

**Comment by micheleRP** [comment]
> We don't really have a docs section for breaking changes, but I think it's worth calling out somewhere obvious such a section on migrating to v23.2.

@BenPope: We do have this new section in the doc: https://docs.redpanda.com/docs/manage/cluster-maintenance/rolling-upgrade/#review-incompatible-changes

**Comment by Feediver1** [comment]
Can you make any other required updates and get this across the finish line @micheleRP ? Thx

**Review by Feediver1 — APPROVED** [review]
lgtm

**Comment by BenPope** [comment]
I was hoping to see a note in the breaking changes section.

**Pull request merged**
