### PR TITLE
Fix bootstrap procedure

### PR DESCRIPTION
**Pull request by JakeSCahill**
Fixes https://github.com/redpanda-data/documentation-private/issues/2295

Tested on Ubuntu.

Also single-sources duplicated information in the prod deployment and dev deployment guides.

Preview: https://deploy-preview-336--redpanda-docs-preview.netlify.app/current/deploy/deployment-option/self-hosted/manual/production/production-deployment/#bootstrapping

### CODE REVIEW

**Comment by supahcraig** [comment]
In this section we have example private IPs given, should those be the "parameterized" <self-IP> like we have for the public IPs further down?

```
redpanda:
  kafka_api:
    - address: 192.168.1.100  # Private IP for internal traffic
      name: internal
      port: 9092
    - address: 0.0.0.0  # Listen on all interfaces for external traffic
      name: external
      port: 9093
  advertised_kafka_api:
    - address: 192.168.1.100  # Advertise internal IP to internal clients
  ```

**Comment by supahcraig** [comment]
Also this line is technically false (as bootstrapping works today), which is why we had to touch these documents in the first place.    Well...maybe not _false_, but misleading.   It puts those values into the yaml, but doesn't put any of them into the correct spots.

```
After bootstrapping Redpanda, your /etc/redpanda/redpanda.yaml configuration file will be updated to include your seed servers and listener addresses.
```

**Comment by supahcraig** [comment]
The format of the yaml given here is not how the actual output looks:

```
redpanda:
    data_directory: /var/lib/redpanda/data
    empty_seed_starts_cluster: false
    seed_servers:
        - host:
            address: <seed-server-ips>
            port: 33145
```

The actual output looks like this, with the seed servers on separate lines.  Or maybe you were just being concise with your example?

```
redpanda:
    data_directory: /var/lib/redpanda/data
    empty_seed_starts_cluster: false
    seed_servers:
        - host:
            address: <seed server #1 IP>
            port: 33145
        - host:
            address: <seed server #2 IP>
            port: 33145
        - host:
            address: <seed server #3 IP>
            port: 33145
```

**Comment by JakeSCahill** [comment]
> Also this line is technically false (as bootstrapping works today), which is why we had to touch these documents in the first place. Well...maybe not _false_, but misleading. It puts those values into the yaml, but doesn't put any of them into the correct spots.
> 
> ```
> After bootstrapping Redpanda, your /etc/redpanda/redpanda.yaml configuration file will be updated to include your seed servers and listener addresses.
> ```

It does include the values passed to `--self` as the listeners though, right? It just doesn't update the advertised listeners.

**Comment by JakeSCahill** [comment]
> In this section we have example private IPs given, should those be the "parameterized" like we have for the public IPs further down?
> 
> ```
> redpanda:
>   kafka_api:
>     - address: 192.168.1.100  # Private IP for internal traffic
>       name: internal
>       port: 9092
>     - address: 0.0.0.0  # Listen on all interfaces for external traffic
>       name: external
>       port: 9093
>   advertised_kafka_api:
>     - address: 192.168.1.100  # Advertise internal IP to internal clients
> ```

To keep this doc succinct, I've removed this section and linked out to our doc on configuring listeners.

**Review by r-vasquez — APPROVED** [review]

**Review by Feediver1 — APPROVED** [review]
Thanks @JakeSCahill !

**Pull request merged**
