### PR TITLE
docs: Fix `rpk` commands and add a warning about reusing node IDs

### LINKED ISSUE #1506: Missing command in decommissioning docs
### Describe the Issue

`rpk admin brokers decommission-status` should be `rpk redpanda admin brokers decommission-status`.

Also, we should warn users not to reuse the ID of the decommissioned node if they add a new broker in the future.

### Updates to existing documentation

https://docs.redpanda.com/docs/manage/cluster-maintenance/decommission-brokers/
https://docs.redpanda.com/docs/manage/kubernetes/decommission-brokers/

### PR DESCRIPTION
**Pull request by JakeSCahill**
Fixes #1506

### CODE REVIEW

**Comment by AnneLeeperRP** [comment]
Just a heads up - 
@r-vasquez told me in a DM "fwiw, we want to get rid of everything inside rpk redpanda admin and move it somewhere else."

**Review by r-vasquez — APPROVED** [review]
LGTM

**Comment by r-vasquez** [comment]
@AnneLeeperRP Yes, but it's not happening this Q :smile:

**Review by Feediver1 — APPROVED** [review]
lgtm

**Pull request merged**
