### PR TITLE
engine: add links to header. fix css rule

### LINKED ISSUE #1724: Add Contact Us option in header for all doc pages
### Describe the Issue

Docs are a critical part of discovery/eval for our customers. Recent leads originated from the docs, but contact us is buried in the footer. Let's add the contact us option in the top nav.
image
 
Can have it contact Sales or  take the Contact menu from main website and replicate it!

image

### PR DESCRIPTION
**Pull request by Deflaimun**
Resolves #1724 

Preview: 
https://deploy-preview-1725--redpanda-documentation.netlify.app/

### CODE REVIEW

**Comment by Deflaimun** [comment]
I have added the contact info as requested. But now we have 2 duplicate entries on the header.
Can I remove those?
image

**Comment by dhruv-gupta** [comment]
We can remove helpdesk. I don't duplicating community for docs.

Also, please use sentence case.

**Comment by Deflaimun** [comment]
@dhruv-gupta there was an ask not long ago, to make it all capitalized just like Redpanda.com

Can you confirm the request to sentence case ?

**Comment by Deflaimun** [comment]
Ah, you want the inside of the dropdown to be sentence case. Got it.

**Review by Feediver1 — APPROVED** [review]

**Pull request merged**
