### PR TITLE
Add tip for multiple principals in comma-separated list

### LINKED ISSUE #1229: Document how-to configure authorization ACLs with rpk for single principal with commas
### Describe the Issue

From RP community: https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1676388972240599 

Community member:
> Hi, I'm trying to configure authorization ACLs as documented here: https://docs.redpanda.com/docs/manage/security/authorization/
However, whenever I create an ACL for a mTLS principal, it splits the principal based on the RDNs, one rule per RDN.  However, that doesn't seem consistent with the documentation here: https://docs.redpanda.com/docs/manage/security/authentication/ which indicates that redpanda matches the entire DN by default. Am I doing something wrong? 

> When I create the ACL, I put single quotes around the principal DN but to no avail, it splits on the commas. I copy and pasted the entire subject field from my cert.

RP replies:
> I got it working with this:

```
openssl x509 -in schema_registry.crt -text -noout | grep Subject:
        Subject: C = UK, ST = London, L = London, O = Redpanda, OU = engineering, CN = __schema_registry

rpk acl create --allow-principal="\"C=UK,ST=London,L=London,O=Redpanda,OU=engineering,CN=__schema_registry\"" --operation all --topic '_schemas' --user admin --password rp123 --sasl-mechanism SCRAM-SHA-256 --brokers 127.0.0.3:19092

rpk topic describe _schemas --brokers 127.0.0.2:19092 --tls-cert schema_registry.crt --tls-key schema_registry.key --tls-truststore mtls_ca.crt
```

> So for me:
Rpk splits on commas, but not inside strings (single or double quote)
Bash strips the double quote
openssl put the spaces in as part of display formatting.

> rpk splits on commas because the thought is to create multiple principals in one go, it wasn’t a design consideration at the time to support a single principal that had commas within it (fwiw)

> backwards incompatible at this point to support that, but we should have documentation for how to create a principal with a comma
> another way of formatting the above be

```
principal='"C=UK,ST=London,L=London,O=Redpanda,OU=engineering,CN=__schema_registry"'
```

### Updates to existing documentation

Update https://docs.redpanda.com/docs/manage/security/authorization/ with tip on principal with multiple commas within rpk

### PR DESCRIPTION
**Pull request by shorgi**
Fixes #1229

### CODE REVIEW

**Comment by Deflaimun** [comment]
Should we add this tip to the rpk command itself?

**Comment by Deflaimun** [comment]
Single source the material to the rpk command too.

**Comment by Deflaimun** [comment]
@JakeSCahill this PR affects versions 22.2, 22.3 and 23.1

**Review by Feediver1 — APPROVED** [review]
lgtm

**Pull request merged**
