### PR TITLE
Simplify the deploy navtree

### PR DESCRIPTION
**Pull request by jrkinley**
This PR addresses issue #1183

### CODE REVIEW

**Comment by Feediver1** [comment]
@Deflaimun Can you please fork/implement for @jrkinley ? Thx.

**Comment by jrkinley** [comment]
@Feediver1 the local `npm run start` didn't flag up the broken links so I need to go through and fix these.

**Comment by Deflaimun** [comment]
@jrkinley `npm run start` doesn't actually run the link checker. 
This is performed by the compiled version `npm run build`

**Comment by shorgi** [comment]
@micheleRP given your work on https://github.com/redpanda-data/documentation/pull/1325, did that PR (and the follow-up issues created from its comments) obviate this one? Should we use this or another PR to continue the implementation of cleaning up the nav tree?

**Comment by micheleRP** [comment]
> @micheleRP given your work on #1325, did that PR (and the follow-up issues created from its comments) obviate this one? Should we use this or another PR to continue the implementation of cleaning up the nav tree?

@shorgi this is still open--it's an issue in epic https://github.com/redpanda-data/documentation/issues/1039

**Comment by micheleRP** [comment]
Sorry, @jrkinley I just realized this is a PR you created. Is it OK with you if I close this because of all the conflicts and start a new issue to fix it? (I'll ask you to review that PR when it's ready.)

**Pull request closed without merging**
