### PR TITLE
New license guidance per Alex

### PR DESCRIPTION
**Pull request by Feediver1**
## Description

Resolves (https://github.com/redpanda-data/documentation-private/issues/2696)
Review deadline: **August 26th**

[Preview](https://deploy-preview-715--redpanda-docs-preview.netlify.app/current/get-started/licenses/#redpanda-enterprise-edition)

## Checks

- [ ] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [x] Small fix (typos, links, copyedits, etc)

### CODE REVIEW

**Comment by micheleRP** [comment]
If we're enforcing the license more now, do we also need to change the section [Check the status of a license](https://deploy-preview-715--redpanda-docs-preview.netlify.app/current/get-started/licenses/#check-the-status-of-a-license) that says, "Redpanda sends warning messages in the cluster logs if you enable enterprise features without a valid license key."?

**Comment by Feediver1** [comment]
> If we're enforcing the license more now, do we also need to change the section [Check the status of a license](https://deploy-preview-715--redpanda-docs-preview.netlify.app/current/get-started/licenses/#check-the-status-of-a-license) that says, "Redpanda sends warning messages in the cluster logs if you enable enterprise features without a valid license key."?

@mattschumpert It's my understanding that we will "gradually" start enforcing licenses. Please advise on exactly what you want the docs to say re this. Thx!

**Comment by Feediver1** [comment]
FYI @emaxerrno

**Review by mattschumpert — APPROVED** [review]

**Review by micheleRP — APPROVED** [review]
lgtm

**Pull request merged**
