### PR TITLE
engine: add redirects to platform  folder

### PR DESCRIPTION
**Pull request by Deflaimun**
Preview : https://deploy-preview-773--redpanda-documentation.netlify.app/

Test links: 

https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/deployment
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/development
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/install-upgrade
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/introduction
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/labs
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/cluster-balancing
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/cluster-property-configuration
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/configuration
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/continuous-data-balancing
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/listener-configuration
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/monitoring
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/node-management
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/cluster-administration/node-property-configuration
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/reference
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features/http-path-rewrites
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features/kafka-connect
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features/programmable-push-filters
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features/protobuf
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features/record-deserialization
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features/schema-registry
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/features/topic-documentation
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/reference/config
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/reference/docker-compose
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/reference/role-bindings
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on/authentication
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on/authorization
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on/identity-providers
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on/identity-providers/generic-oidc
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on/identity-providers/github
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on/identity-providers/google
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/console/single-sign-on/identity-providers/okta
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management/data-archiving
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management/data-migration
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management/rack-awareness
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management/rack-awareness.module.css
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management/remote-read-replicas
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/data-management/tiered-storage
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/deployment/custom-deployment
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/deployment/disk-utilization
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/deployment/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/deployment/io-optimization
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/deployment/production-deployment-automation
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/deployment/production-deployment
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/development/consumer-offsets
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/development/guide-nodejs
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/development/http-proxy
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/development/idempotent-producers
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/development/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/development/kafka-clients
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/install-upgrade/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/install-upgrade/rolling-upgrade
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/install-upgrade/start-streaming
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/install-upgrade/version-upgrade
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/introduction/autotune
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/introduction/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/introduction/intro-to-events
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/introduction/licenses
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/labs/data-transform
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/labs/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/labs/install-preview
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/console-installation
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/kubernetes-qs-dev
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/quick-start-docker
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/quick-start-linux
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/quick-start-macos
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/quick-start-windows
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/quickstart/rpk-install
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/cluster-properties
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/internal-metrics
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/node-configuration-sample
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/node-properties
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/tunable-properties
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/arbitrary-configuration
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-additional-config
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-connectivity
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-external-connect
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-mtls
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-qs-cloud
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-qs-local-access
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-qs-minikube
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/kubernetes-sasl
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/security-kubernetes
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/redpanda-operator/tls-kubernetes
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-commands
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-container
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-debug
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-generate
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-group
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-help
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-iotune
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-plugin
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-version
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-wasm
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl-create
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl-delete
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl-user-create
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl-user-delete
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl-user-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl-user
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-acl/rpk-acl
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-edit
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-export
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-force-reset
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-get
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-import
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-lint
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-set
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config-status
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-config
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-health
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-license-info
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-license-set
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-license
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-logdirs-describe
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-logdirs
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-maintenance-disable
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-maintenance-enable
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-maintenance-status
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-maintenance
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-metadata
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-partitions-balancer-status
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-partitions-movement-cancel
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster-partitions
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-cluster/rpk-cluster
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-container/rpk-container-purge
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-container/rpk-container-start
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-container/rpk-container-stop
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-container/rpk-container
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-debug/rpk-debug-bundle
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-debug/rpk-debug
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-generate/rpk-generate-grafana-dashboard
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-generate/rpk-generate-prometheus-config
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-generate/rpk-generate-shell-completion
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-generate/rpk-generate
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-group/rpk-group-delete
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-group/rpk-group-describe
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-group/rpk-group-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-group/rpk-group-seek
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-group/rpk-group
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-plugin/rpk-plugin-install
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-plugin/rpk-plugin-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-plugin/rpk-plugin-uninstall
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-plugin/rpk-plugin
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers-decommission
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers-recommission
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-brokers
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-config-log-level-set
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-config-log-level
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-config-print
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-config
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-partitions-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin-partitions
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-admin
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-check
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-config-bootstrap
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-config-init
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-config-set
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-config
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-mode
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-start
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-stop
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-tune-help
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-tune-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda-tune
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-redpanda/rpk-redpanda
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-add-partitions
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-alter-config
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-consume
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-create
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-delete
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-describe
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-list
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic-produce
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-topic/rpk-topic
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-wasm/rpk-wasm-deploy
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-wasm/rpk-wasm-generate
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-wasm/rpk-wasm-remove
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/reference/rpk/rpk-wasm/rpk-wasm
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security/authentication
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security/authorization
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security/encryption
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security/iam-roles
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security/index
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security/kubernetes-tls
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/security/sasl-kubernetes

### CODE REVIEW

**Comment by Feediver1** [comment]
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/output.txt
still throws a **Page Not Found**

**Comment by Feediver1** [comment]
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/console/features Still throwing **Page Not Found**

**Comment by Feediver1** [comment]
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/console/reference Still throwing **Page Not Found**

**Comment by Feediver1** [comment]
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/console/single-sign-on Still throwing **Page Not Found**.

**Comment by Feediver1** [comment]
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/console/single-sign-on/identity-providers Still shows **Page Not Found**

**Comment by Feediver1** [comment]
https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/data-management/rack-awareness.module.css Still shows **Page Not Found**

**Review by Feediver1 — APPROVED** [review]
@Deflaimun See the Conversation tab for all my comments re links that still fail. After fixing those, you can go ahead and merge. Thanks!

**Comment by Deflaimun** [comment]
> https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/output.txt 
> https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/data-management/rack-awareness.module.css
> 

Those are mistakes and shouldn't be on the list.

**Comment by Deflaimun** [comment]
> https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/console/features 
> https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/console/single-sign-on 

Those have problems with the Style guide. There should be indexes files for them.

> https://deploy-preview-773--redpanda-documentation.netlify.app/docs/platform/console/single-sign-on/identity-providers 
This is a mistake about using our folder structure. Style guide--ish issue too.

**Pull request merged**
