### PR TITLE
Removed the duplicate rpk container page

### PR DESCRIPTION
**Pull request by rkruze**
It now redirects to the macOS guide which uses rpk container. Outside of macOS `rpk container` is not normally used. 

Also updated the versioned docs to point to the right version of the previous `rpk container` page.

### CODE REVIEW

**Comment by Feediver1** [comment]
@Deflaimun Doesn't this need a redirect for the removal of the Starting a Local Cluster topic? If so, can you add that here? I suspect that @rkruze is not familiar with the redirect requirements. Thanks.

**Comment by rkruze** [comment]
@Feediver1 I updated the `_redirect` file which seems to work on the preview link, is more needed on top of that? 

You can try it here: `https://deploy-preview-686--redpanda-documentation.netlify.app/docs/deployment/guide-rpk-container`

**Comment by Deflaimun** [comment]
Everything looks good, except for the link changes. They're already covered in https://github.com/redpanda-data/documentation/pull/687

**Comment by Deflaimun** [comment]
I have fixed the PR. It can be merged now.

**Review by Feediver1 — APPROVED** [review]
Thanks @rkruze and @Deflaimun

**Pull request merged**
