### PR TITLE
Change names to reflect upcoming Deployment Automation changes

### PR DESCRIPTION
**Pull request by gene-redpanda**
Updates the names to reflect changes in https://github.com/redpanda-data/deployment-automation/pull/218

### CODE REVIEW

**Comment by Deflaimun** [comment]
Is this for 24.1 or 23.3 ? @gene-redpanda

**Comment by gene-redpanda** [comment]
> Is this for 24.1 or 23.3 ? @gene-redpanda

Unrelated to RP release versions.

**Review by Deflaimun — APPROVED** [review]

**Review by Deflaimun — APPROVED** [review]

**Comment by gene-redpanda** [comment]
@Deflaimun this was not ready for merge yet, please revert.

**Comment by Deflaimun** [comment]
Reopened at https://github.com/redpanda-data/docs/pull/458

**Pull request merged**
