### PR TITLE
engine: Editable placeholders

### PR DESCRIPTION
**Pull request by JakeSCahill**
Writers use placeholders in code blocks to indicate where a user must add their own values. When we include placeholders in our code blocks, the user must copy/paste the code, then remember to replace the placeholder values.

This PR introduces the ability to edit the placeholders within the browser. Users can work directly within the docs, and when they're ready to run the example, they can copy/paste the code along with their custom values.

This PR swizzles the `CodeBlock` and `CodeBlock/CopyButton` components. The `CodeBlock` component is considered safe, but the `CodeBlock/CopyButton` component is not. The change to `CodeBlock/CopyButton` is minor, but we will still need to be mindful that we may need to update the `CopyButton` code ourselves if Docusaurus release a new version that updates this component.

Preview: https://deploy-preview-1316--redpanda-documentation.netlify.app/docs/get-started/licenses/#apply-a-license-key-to-redpanda

The cursor is intentionally light to avoid distracting users while they read.

### CODE REVIEW

**Comment by Deflaimun** [comment]
@JakeSCahill which components were created vs. swizzled?

**Comment by Deflaimun** [comment]
This is awesome. I would encourage you to create a PR against https://github.com/facebook/docusaurus itself. 
They would probably appreciate it!

**Comment by Deflaimun** [comment]
I've only found one instance where this can get bugged
https://docs.redpanda.com/docs/get-started/licenses/

The code block itself is not great. But it looks like the regex is fetching for <>  

```
Looks like you’ve enabled a Redpanda Enterprise feature without a valid license. Please enter an active Redpanda license key (e.g. rpk cluster license set <key>). If you don’t have one, please request a new/trial license at https://redpanda.com/license-request.
```

**Comment by JakeSCahill** [comment]
aha thanks @Deflaimun - this seems to be an edge case that I didn't expect. Docusaurus sometimes puts everything into a single span 😱 



I'll work on this case tomorrow.

**Comment by JakeSCahill** [comment]
I also want to try to add a cursor at the end of the editable part so that users can see it's editable 😄

**Review by Deflaimun — APPROVED** [review]
LGTM! This is awesome thanks @JakeSCahill. 

Good test pages: 
https://deploy-preview-1316--redpanda-documentation.netlify.app/docs/get-started/code-examples/

https://deploy-preview-1316--redpanda-documentation.netlify.app/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment/

https://deploy-preview-1316--redpanda-documentation.netlify.app/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation/

**Comment by shorgi** [comment]
@JakeSCahill found a corner case, with Java class args like `Producer<String, String>` on this page:

https://docs.redpanda.com/docs/develop/transactions/

**Pull request merged**
