### PR TITLE
Page eol

### PR DESCRIPTION
**Pull request by Deflaimun**
Resolves https://github.com/redpanda-data/documentation-private/issues/2075

Should only be merged on Nov 12th

### CODE REVIEW

**Comment by Feediver1** [comment]
Remind me to approve on Nov 12 @Deflaimun so that this does not get merged before then. Thanks!

**Comment by mattschumpert** [comment]
@Deflaimun , @Feediver1  please wait on merging this. We may push back the date

**Comment by Feediver1** [comment]
No need to rewrite. I think we need an admonition specific to/only displayed for EOL though. 
Does this ticket take care of automation? In other words, when we release 23.3, will this header automatically replace the 23.2 with 23.3 and so on?

**Comment by JakeSCahill** [comment]
Yes this is automated. Also the message is different in the admonition for EoL versions

**Comment by JakeSCahill** [comment]
@mattschumpert did we go ahead with the EoL for 22.3?

**Comment by Deflaimun** [comment]
Last into on this is Dec 15th

**Comment by mattschumpert** [comment]
To be clear, we can add the banner that says it WILL go end of life in Dec 15th, just not a banner saying it IS end of Life

**Comment by mattschumpert** [comment]
@Deflaimun 
It might be helpful to merge this now to alert more customers (text that says it WILL go end of life on Dec 15th).

**Comment by mattschumpert** [comment]
why is this 'blocked?

**Comment by Deflaimun** [comment]
@Feediver1

**Comment by Feediver1** [comment]
Blocked to prevent it being merged before the requested merge date. 

Also, if the update takes effect on Dec 15th, then we should push out on Dec 15th. Docs do not refer to anything that "will" happen in the future. Given the team is pushing to meet the Dec 22nd release deadline, let's merge this once on Dec 15th, as requested.

**Review by Feediver1 — APPROVED** [review]

**Pull request merged**
