### PR TITLE
Update k-troubleshoot.adoc

### PR DESCRIPTION
**Pull request by jm-nab**
usageStats was a required object?

### CODE REVIEW

**Review by RafalKorepta — COMMENTED** [review]
In my opinion we should fix Redpanda custom resource definition to not be strict on `usageStats`. 

Thoughts @alejandroEsc @chrisseto?

**Comment by chrisseto** [comment]
> In my opinion we should fix Redpanda custom resource definition to not be strict on usageStats.

Agreed there. Is this enforced by the CRD's validation or by the helm chart's validation?

**Comment by RafalKorepta** [comment]
> > In my opinion we should fix Redpanda custom resource definition to not be strict on usageStats.
> 
> Agreed there. Is this enforced by the CRD's validation or by the helm chart's validation?

The `usageStats` is missing `omitempty` yaml annotation. 

https://github.com/redpanda-data/redpanda-operator/blob/27cc0a0445d8ac1c4e596d38ce5dc5ace064e8ed/src/go/k8s/api/redpanda/v1alpha1/redpanda_clusterspec_types.go#L392

Because of that Redpanda CRD has this field as required:

https://github.com/redpanda-data/redpanda-operator/blob/27cc0a0445d8ac1c4e596d38ce5dc5ace064e8ed/src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml#L1163-L1165

**Comment by JakeSCahill** [comment]
> > > In my opinion we should fix Redpanda custom resource definition to not be strict on usageStats.
> > 
> > 
> > Agreed there. Is this enforced by the CRD's validation or by the helm chart's validation?
> 
> The `usageStats` is missing `omitempty` yaml annotation.
> 
> https://github.com/redpanda-data/redpanda-operator/blob/27cc0a0445d8ac1c4e596d38ce5dc5ace064e8ed/src/go/k8s/api/redpanda/v1alpha1/redpanda_clusterspec_types.go#L392
> 
> Because of that Redpanda CRD has this field as required:
> 
> https://github.com/redpanda-data/redpanda-operator/blob/27cc0a0445d8ac1c4e596d38ce5dc5ace064e8ed/src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml#L1163-L1165

https://github.com/redpanda-data/redpanda-operator/pull/100

**Comment by JakeSCahill** [comment]
closing this as we plan to fix on the operator side.

**Pull request closed without merging**
